apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - www.daveevans.us
    - www.terraform-provider-flash.com
    - www.footprintsblog.com
    secretName: letsencrypt-prod
  rules:
  - host: www.daveevans.us
    http:
      paths:
      - backend:
          serviceName: blog
          servicePort: 80
  - host: www.terraform-provider-flash.com
    http:
      paths:
      - backend:
          serviceName: terraform-provider-flash-website
          servicePort: 80
  - host: www.footprintsblog.com
    http:
      paths:
      - backend:
          serviceName: footprintsblog
          servicePort: 80
