baseURL = "https://www.daveevans.us/"
title = "Dave Evans"
googleAnalytics = "UA-124360075-1"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "www-daveevans-us"


[params]
    author = "Dave Evans"
    info = "Sysadmin and Linux Enthusiast"
    description = "Dave Evans' personal website"
    keywords = "blog,devops,personal"
    avatarurl = "img/avatar.jpg"

    favicon_32 = "/img/favicon.ico"
    favicon_16 = "/img/favicon.ico"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

[[menu.main]]
  name = "Tech"
  url = "/posts/"
  weight = 1
[[menu.main]]
  name = "Personal"
  url = "/personal/"
  weight = 2
[[menu.main]]
  name = "About"
  weight = 3
  url = "/about/"
[[menu.main]]
  name = "Projects"
  weight = 4
  url = "/projects/"

[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 1
    url = "https://twitter.com/dave_evans67"
[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 2
    url = "https://github.com/devans10"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-gitlab"
    weight = 3
    url = "https://gitlab.com/devans10/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/david-evans-5a6156b4/"
