name: Deploy
on: [push]
jobs:
  DeploySite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H www.daveevans.us >> ~/.ssh/known_hosts

      - name: install Hugo
        run: sh ./cicd/install_hugo.sh
        
      - name: Run Deploy
        run: sh ./cicd/deploy.sh